# SwiftLint Configuration
# Matches Senior iOS Developer Profile Standards

# Files to include/exclude
included:
  - .
excluded:
  - Carthage
  - Pods
  - Build
  - .build
  - DerivedData

# Rule Configuration
line_length:
  warning: 150
  error: 160
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 350
  error: 400

function_body_length:
  warning: 40
  error: 50

closure_body_length:
  warning: 40
  error: 47

type_body_length:
  warning: 200
  error: 250

function_parameter_count:
  warning: 4
  error: 5

identifier_name:
  min_length: 2
  max_length: 40
  validates_start_with_lowercase: true

type_name:
  min_length: 3
  max_length: 40

# Enabled Rules (Opt-in)
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled Rules
disabled_rules:
  - todo # We want TODOs to follow specific format
  - trailing_comma # Allow trailing commas

# Custom Rules
custom_rules:
  todo_format:
    name: "TODO Format"
    regex: '(TODO|FIXME)(?!: [A-Z]+-\d+ • )'
    message: "TODOs must follow format: TODO: JIRA-1234 • Description"
    severity: warning

# Specific Rule Configurations
trailing_whitespace:
  ignores_empty_lines: false

vertical_whitespace:
  max_empty_lines: 1

attributes:
  always_on_same_line: 
    - "@IBAction"
    - "@IBOutlet"
    - "@IBInspectable"
    - "@GKInspectable"
    - "@NSManaged"
    - "@objc"
    - "@nonobjc"
  always_on_line_above:
    - "@discardableResult"
    - "@MainActor"
    - "@Sendable"
    - "@available"

implicit_return:
  included:
    - closure
    - function
    - getter

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

multiline_function_chains:
  only_enforce_after_first_closure_on_first_line: true

multiline_parameters:
  allows_single_line: true

sorted_imports:
  group_imports_by_module: true

force_unwrapping:
  severity: error

implicitly_unwrapped_optional:
  severity: error